import Head from "next/head";

export default function DefaultHeader() {
    return (
        <>
            <Head>
                <title>the People's Purse</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                {/* <link rel='canonical' href='https://thepeoplespurse.org' /> */}
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
            </Head>
        </>
    )
}