import {
  useQuery,
  gql
} from '@apollo/client';
import Head from 'next/head';
import AllVotesCharts from '../components/allVotesChart';
// import ClassSelect from '../components/classSelect';

const ALL_VOTES = gql`
query Query {
  allVotes {
    totalVotes
    aggVotes {
      _id
      percent
    }
  }
}
`

export default function BudgetResults() {
  const { loading, error, data } = useQuery(ALL_VOTES);
  if (data) {
    const allVotes = data.allVotes
    console.log(allVotes)
  }
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :( {JSON.stringify(error)}</p>;
  return (
    <>
      <Head>
        <title>the People's Purse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
      </Head>
      <div id='chart'>
        <AllVotesCharts />
      </div>
    </>
  )
}